### ISSUE TITLE
SSH Keys not found

### ISSUE THREAD

**Issue by iamarasekera** [tmate-io/tmate.io#13]
I tried to install tmate on a MacBook Pro  with Sierra (10.12.4).  
I successfully installed Homebew and tmate.

When I tried to run tmate, it says SSH keys not found, run 'ssh-keygen' to create SSH key and then try again.  Please refer the below image.

<img width="974" alt="Screen Shot 2019-06-25 at 6 34 48 PM" src="https://user-images.githubusercontent.com/7510059/60092384-7ddd4180-9779-11e9-8dc8-98173caf7132.png">

I already had SSH key created on my system yet, deleted that and created a new one and tried again.

Then it prompted me with "sessions should be nested with care, unset $TMUX to force" and I have no clear idea how to eliminate that. I have tried few workarounds suggested by other users but nothing fixed my issue. Also, I keep getting SSH key not found error. Tmate keeps trying to reconnect to SSH and it is not happening. Please refer the below image.

<img width="976" alt="Screen Shot 2019-06-25 at 6 36 58 PM" src="https://user-images.githubusercontent.com/7510059/60092394-86357c80-9779-11e9-9e69-8294331d17b3.png">

**Comment by nviennot** [comment]
exit tmate, and relaunch tmate. If this doesn't work, I'm not sure why.

**Comment by iamarasekera** [comment]
Okay. I figured out what causes it. 

In Mac, when you use `ssh-keygen -t rsa` to generate a SSH key and it prompts you to enter file in which to save the key `(/Users/iamarasekera/.ssh/id_rsa):` and If you enter a file name there, it creates 2 file as `<filename>` and `<filename>.pub` inside the directory where you are currently located without creating a `.ssh folder`.

Therefore, tmate cannot locate the SSH keys because they are not inside the .ssh folder.

**Solution :** 

When you use ssh-keygen -t rsa to generate a SSH key and it prompts you to

`Enter file in which to save the key (/Users/iamarasekera/.ssh/id_rsa):`

> Do not give any file name. Instead, just press "Enter" key and go ahead. 

Then it will create .ssh folder and inside that folder it will generate the 2 files id_rsa and id_rsa.pub. You will also see the message Created directory '/<path to your current folder>/.ssh'. on your command prompt.
Next, it will prompt you toEnter passphraseand you better not skip it.

After that your ssh keys will be created inside a `.ssh folder` and tmate can be used without any issue.
