### ISSUE TITLE
FreeBSD install instructions

### ISSUE THREAD

**Issue by swills** [tmate-io/tmate.io#4]
Hi,

I've ported tmate and the server for it to FreeBSD. Please update https://tmate.io to add instructions for installing on FreeBSD. The process is simply: `pkg install tmate`. Thanks!

Steve

**Comment by nviennot** [comment]
Hi Steve,

I've added the FreeBSD install instructions on the homepage, check it out.
I've also included the two `#include` that you've added in the sources: https://github.com/tmate-io/tmate/commit/27169b7c076376718abf98f7a1a6b484bd579314 so the next release, you won't need to apply any patches :)

Thank you,
Nico

**Comment by swills** [comment]
Great, thank you so much!
